Parse statements until EOF
imteekay/mini-typescript-fork pull request #7
Opened 2023-05-02 19:10 UTC by imteekay

2023-05-08 23:21 UTC, sandersn requested changes

2023-05-08 23:21 UTC, sandersn commented on src/check.ts
> +const eof: Type = { id: 'eof' };
these should probably be the same type, probably `undefined`, since I think that's what empty statements return in javascript.

2023-05-08 23:21 UTC, sandersn commented on src/types.ts
> +  | EndOfFile;
I don't understand why a EndOfFile statement or node is needed

2023-05-08 23:21 UTC, sandersn commented on src/parse.ts
> +    while (lexer.token() !== Token.EOF) {
I think this function should be the one checking for semicolons, not parseStatement.
Although it would be best to pass in a predicate like `separator`, except named `terminator` or something.

2023-05-16 01:48 UTC, imteekay commented on src/types.ts
> +  | EndOfFile;
Agreed! Just removed it https://github.com/imteekay/mini-typescript/pull/7/commits/b74b6fc8e0f1efe7c3f1c7b54118d0e658177942

2023-05-16 01:48 UTC, imteekay commented on src/check.ts
> +const eof: Type = { id: 'eof' };
Agreed! Just removed it https://github.com/imteekay/mini-typescript/pull/7/commits/b74b6fc8e0f1efe7c3f1c7b54118d0e658177942

2023-05-16 01:56 UTC, imteekay commented on src/parse.ts
> +    while (lexer.token() !== Token.EOF) {
Not sure if I got the exercise right this time. https://github.com/imteekay/mini-typescript/pull/7/commits/b74b6fc8e0f1efe7c3f1c7b54118d0e658177942

The whole idea was
- Add a predicate function (`terminator`) to handle semicolons
- after a semicolon, we can have
  - another semicolon: I considered that an empty statement (https://github.com/imteekay/mini-typescript/pull/2)
    - just added a `peek` function to see the next token and if it's indeed a semicolon, call the parse statement to get the `EmptyStatement` node
  - the rest of the tokens (string, number, eof): just parse a statement

Does that make sense? Maybe it can be improved for this particular case.

2023-05-16 01:56 UTC, imteekay commented on src/parse.ts
> +    while (lexer.token() !== Token.EOF) {
@sandersn Not sure if I got the exercise right this time. https://github.com/imteekay/mini-typescript/pull/7/commits/b74b6fc8e0f1efe7c3f1c7b54118d0e658177942

The whole idea was
- Add a predicate function (`terminator`) to handle semicolons
- after a semicolon, we can have
  - another semicolon: I considered that an empty statement (https://github.com/imteekay/mini-typescript/pull/2)
    - just added a `peek` function to see the next token and if it's indeed a semicolon, call the parse statement to get the `EmptyStatement` node
  - the rest of the tokens (string, number, eof): just parse a statement

Does that make sense? Maybe it can be improved for this particular case.

2023-05-31 22:51 UTC, sandersn commented on src/parse.ts
> +    while (lexer.token() !== Token.EOF) {
Here's the way Typescript does it, as I recall:

```js
const list = []
while (peek()) {
  list.push(element())
  terminator()
}
```

where `peek` returns true if the current token could be the start of a new Statement, and `terminator` doesn't consume a token if terminators are optional. This relies on the first token of statements to be distinguishable from from non-statements, but the only non-statement that can come after a statement list is Token.EOF, so `peek` is just going to be `() => lexer.token !== Token.EOF`

This way is a bit simpler than yours, and generalises to other kinds of lists, like parameter lists, arrays, etc.

2023-06-27 01:29 UTC, imteekay commented on src/parse.ts
> +    while (lexer.token() !== Token.EOF) {
Simplified it, the implementation seems much better now! ✨  https://github.com/imteekay/mini-typescript/pull/7/commits/cad1fec3f754c960eeecccd36dd1fd7869053819

2023-07-06 10:41 UTC, merged